# SPIGOTMODDING configuration
# This file allows you to change how the spigotmodding plugin works

# If an error occurs and these setting are true, the server will be shut down
shutDownServerOnError:
  modVersionError: true
  modNamespaceCollision: true
  modDoubleNamespaces: true