name: NetherReactor
version: '${project.version}'
main: me.mythicalflame.netherreactor.NetherReactorModLoader
api-version: 1.18
load: STARTUP
authors: [ MythicalFlame ]
description: Spigot modding framework for custom blocks and items
commands:
  netherreactor:
    description: Main command for NetherReactor
    usage: /netherreactor <subCommand>
permissions:
  netherreactor.commandnetherreactor.give:
    description: Allows the user to use the netherreactor give command to give custom items.
    default: op
  netherreactor.commandnetherreactor.items:
    description: Allows the user to use the netherreactor items command to see the list of registered items.
    default: true
  netherreactor.commandnetherreactor.item:
    description: Allows the user to use the netherreactor item command to inspect an item.
    default: true
  netherreactor.commandnetherreactor.*:
    description: Allows the user to use the netherreactor command and its subcommands.
    default: false