name: SpigotModding
version: '${project.version}'
main: me.mythicalflame.spigotmodding.SpigotModding
api-version: 1.17
load: STARTUP
authors: [ MythicalFlame ]
description: Spigot modding framework for custom blocks and items
commands:
  spigotmodding:
    description: Main command for spigotmodding
    usage: /spigotmodding <subCommand>
permissions:
  spigotmodding.commandspigotmodding:
    description: Allows the user to user the spigotmodding command to see the item list and give them.
    default: op
    children:
      spigotmodding.commands.spigotmodding: true