name: SpigotModding
version: '${project.version}'
main: me.mythicalflame.spigotmodding.SpigotModding
api-version: 1.17
load: STARTUP
authors: [ MythicalFlame ]
description: Spigot modding framework for custom blocks and items
commands:
  spigotmodding:
    description: Main command for spigotmodding
    usage: /spigotmodding <subCommand>
permissions:
  spigotmodding.commandspigotmodding.give:
    description: Allows the user to use the spigotmodding give command to give custom items.
    default: op
  spigotmodding.commandspigotmodding.items:
    description: Allows the user to use the spigotmodding items command to see the list of registered items.
    default: true
  spigotmodding.commandspigotmodding.item:
    description: Allows the user to use the spigotmodding item command to inspect an item.
    default: true
  spigotmodding.commandspigotmodding.*:
    description: Allows the user to use the spigotmodding command and its subcommands.
    default: false