name: NetherReactor
version: '${project.version}'
main: me.mythicalflame.netherreactor.NetherReactorModLoader
api-version: '1.21.4'
load: STARTUP
authors: [ MythicalFlame ]
description: Modding framework for custom items
commands:
  netherreactor:
    description: Main command for NetherReactor
    usage: /netherreactor <subCommand>
permissions:
  netherreactor.command.netherreactor.give:
    description: Allows the user to use the netherreactor give command to give custom items.
    default: op
  netherreactor.command.netherreactor.items:
    description: Allows the user to use the netherreactor items command to see the list of registered items.
    default: true
  netherreactor.command.netherreactor.item:
    description: Allows the user to use the netherreactor item command to inspect an item.
    default: true
  netherreactor.command.netherreactor.mods:
    description: Allows the user to use the netherreactor mods command to see the list of registered mods.
    default: true
  netherreactor.command.netherreactor.mod:
    description: Allows the user to use the netherreactor mod command to inspect a mod.
    default: true
  netherreactor.command.netherreactor.creative:
    description: Allows the user to use the netherreactor creative command to open the creative inventory.
    default: false
  netherreactor.command.netherreactor.itemlookup:
    description: Allows the user to use the netherreactor itemlookup command to open the item lookup interface.
    default: true
  netherreactor.command.netherreactor.*:
    description: Allows the user to use the netherreactor command and its subcommands.
    default: false